<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>ru.i-novus.components</groupId>
        <artifactId>versioned-data-storage</artifactId>
        <version>3.26-SNAPSHOT</version>
    </parent>

    <artifactId>versioned-data-storage-ee-adapter</artifactId>
    <packaging>jar</packaging>

    <properties>
        <jakartaee-api.version>9.0.0</jakartaee-api.version>
    </properties>

    <dependencies>
        <dependency>
            <groupId>ru.i-novus.components</groupId>
            <artifactId>versioned-data-storage-api</artifactId>
            <version>${project.parent.version}</version>
        </dependency>

        <dependency>
            <groupId>ru.i-novus.components</groupId>
            <artifactId>versioned-data-storage-pg-impl</artifactId>
            <version>${project.parent.version}</version>
        </dependency>

        <dependency>
            <groupId>jakarta.transaction</groupId>
            <artifactId>jakarta.transaction-api</artifactId>
        </dependency>

        <dependency>
            <groupId>jakarta.platform</groupId>
            <artifactId>jakarta.jakartaee-api</artifactId>
            <version>${jakartaee-api.version}</version>
            <scope>provided</scope>
        </dependency>
    </dependencies>

</project>